_BASE_: [
  '../datasets/data_coco_detection.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/ppyoloe_crn.yml',
  './_base_/ppyoloe_reader.yml',
]

log_iter: 100
snapshot_epoch: 10
epoch: 150
weights: output/ppyoloe_crn_l_300e_coco/model_final
find_unused_parameters: True

pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyoloe_crn_m_300e_coco.pdparams
depth_mult: 0.67
width_mult: 0.75

TrainReader:
  batch_size: 24

LearningRate:
  base_lr: 0.008
  schedulers:
    - !CosineDecay
      max_epochs: 360
    - !LinearWarmup
      start_factor: 0.001
      steps: 2300